CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS project_schema;
CREATE SCHEMA IF NOT EXISTS task_schema;
CREATE SCHEMA IF NOT EXISTS team_schema;
CREATE SCHEMA IF NOT EXISTS notification_schema;