CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS company_db;
CREATE DATABASE IF NOT EXISTS project_db;
CREATE DATABASE IF NOT EXISTS task_db;
CREATE DATABASE IF NOT EXISTS team_db;
CREATE DATABASE IF NOT EXISTS notification_db;