FROM postgres:16

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-16-cron \
    && rm -rf /var/lib/apt/lists/*

COPY postgresql.conf /etc/postgresql/16/main/postgresql.conf
COPY ./init-scripts /docker-entrypoint-initdb.d/