
networks:
  quadro-net:
    driver: bridge

x-common-env: &common-env
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${DB_NAME}
  DB_NAME: ${DB_NAME}
  DB_POOL_SIZE: ${DB_POOL_SIZE:-10}
  KAFKA_BROKERS: kafka:${KAFKA_INTERNAL_PORT:-29092}
  JWT_SECRET: ${JWT_SECRET}
  JWT_ISSUER: ${JWT_ISSUER:-quadro}
  JWT_AUDIENCE: ${JWT_AUDIENCE:-quadro-api}
  JWT_REALM: ${JWT_REALM:-quadro}
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  AUTH_SERVICE_URL: http://auth-service:8081
  COMPANY_SERVICE_URL: http://company-service:8082
  TEAM_SERVICE_URL: http://team-service:8083
  PROJECT_SERVICE_URL: http://project-service:8084
  TASK_SERVICE_URL: http://task-service:8085
  NOTIFICATION_SERVICE_URL: http://notification-service:8086
  ACTIVITY_SERVICE_URL: ${ACTIVITY_SERVICE_URL:-http://activity-service:8087}


volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME:-postgres_data}
  kafka_data:
    name: ${KAFKA_VOLUME:-kafka_data}
  redis_data:
    name: ${REDIS_VOLUME:-redis_data}
  minio_data:
    name: ${MINIO_VOLUME:-minio_data}

services:
  # ========== PostgreSQL ==========
  postgres:
    image: postgres-with-init:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      <<: *common-env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - quadro-net

  # ========== Kafka ==========
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "${KAFKA_PORT_INTERNAL:-29092}:29092"
      - "${KAFKA_PORT_EXTERNAL:-9092}:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_INTERNAL_HOST:-kafka}:${KAFKA_INTERNAL_PORT:-29092},PLAINTEXT_HOST://${KAFKA_EXTERNAL_HOST:-localhost}:${KAFKA_EXTERNAL_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR:-1}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NODE_ID: ${KAFKA_NODE_ID:-1}
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-cx33_hoaQrG0wLT9oWx4Gw}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES:-controller,broker}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_VOTERS:-1@kafka:9093}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_INTERNAL_HOST:-kafka}:${KAFKA_INTERNAL_PORT:-29092},PLAINTEXT_HOST://0.0.0.0:${KAFKA_EXTERNAL_PORT:-9092},CONTROLLER://${KAFKA_CONTROLLER_HOST:-kafka}:${KAFKA_CONTROLLER_PORT:-9093}
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:${KAFKA_EXTERNAL_PORT:-9092} --list" ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - quadro-net

  # ========== Redis ==========

  # ========== MinIO ==========

  # ========== API Gateway ==========
  auth-service:
#    build: ./auth-service
    image: ${DOCKERHUB_USERNAME}/quadro-platform:auth-service.${VERSION:-latest}
    container_name: auth-service
    environment:
      <<: *common-env
      DB_SCHEMA: ${DB_SCHEMA:-auth_schema}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quadro-net

  company-service:
#    build: ./company-service
    image: ${DOCKERHUB_USERNAME}/quadro-platform:company-service.${VERSION:-latest}
    container_name: company-service
    environment:
      <<: *common-env
      DB_SCHEMA: ${DB_SCHEMA:-company_schema}
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quadro-net

  api-gateway:
    image: ${DOCKERHUB_USERNAME}/quadro-platform:api-gateway.${VERSION:-latest}
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "${API_GATEWAY_PORT:-80}:8080"
    depends_on:
      - auth-service
      - company-service
#      - project-service
#      - task-service
#      - team-service
#      - notification-service
#      - redis
    networks:
      - quadro-net