ktor {
  application {
    modules = ["com.quadro.ApplicationKt.module"]
  }
  deployment {
    port = 8080
  }
}

database {
  driver = "org.postgresql.Driver"
  jdbcURL = "jdbc:postgresql://localhost:5432/quadro_db"
  username = "postgres"
  password = "postgres"
  connectionPool {
    maximumPoolSize = 10
    minimumIdle = 2
    connectionTimeout = 30000
    idleTimeout = 600000
    maxLifetime = 1800000
  }
}

jwt {
  issuer = "https://quadro-jwt/"
  audience = "quadro server"
  realm = "ktor quadro app"
  secret = "9T,c]ojP0>vCd0mLCEMNHN:SL)OZ6OC?(-0{:H17&uNfsivcCTE[_%q5+6)*t1u9itbelJD7$BVQz&-ZIK3f9w"
  accessExpiration = 3600000
  refreshExpiration = 86400000
}