ktor:
    deployment:
      port: 8082
    application:
        modules:
        - com.quadro.company.ApplicationKt.module

app:
    jwt:
        secret: "test"
        issuer: "gateway"
        audience: "client"
        access_ms: 3600000
        refresh_ms: 604800000
        invitation_ms: 604800000
    kafka:
        bootstrap_servers: "localhost:9092"
    database:
        url: "jdbc:postgresql://localhost:5432/quadro_db"
        user: "postgres"
        password: "postgres"
        schema: "company_schema"
    redis:
        host: "localhost"
        port: 6379