ktor:
    deployment:
        port: $PORT:8084
    application:
        modules:
        - com.quadro.project.ApplicationKt.module

app:
    jwt:
        secret: "$APP_JWT_SECRET:test"
        issuer: "$APP_JWT_ISSUER:quadro"
        audience: "$APP_JWT_AUDIENCE:quadro-api"
        realm: "$APP_JWT_REALM:quadro"
        access_ms: "$APP_JWT_EXPIRATION_MS:3600000"
        refresh_ms: "$APP_JWT_REFRESH_EXPIRATION_MS:604800000"
    kafka:
        bootstrap_servers: "$APP_KAFKA_BROKERS:localhost:9092"
    database:
        url: ${APP_DATABASE_URL:jdbc:postgresql://localhost:5432/quadro_db}
        user: "$APP_DB_USER:postgres"
        password: "$APP_DB_PASSWORD:postgres"
        schema: "$APP_DATABASE:project_schema"
    redis:
        host: "localhost"
        port: 6379